puts "The students of my cohort at Makers Academy"
puts "-------------"
puts "Dr. Hannibal Lecter"
puts "Darth Vader"
puts "Nurse Ratched"
puts "Michael Corleone"
puts "Alex de Large"
puts "The Alien"
puts "Freddy Kruger"
puts "The Joker"